# Generated by Django 6.0.4 on 2026-04-21 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_testmodel_alter_movimiento_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestModel',
            new_name='PruebaConexionSQL',
        ),
    ]
